// Centralized language constants to avoid duplication across the app

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Polish",
  "Russian",
  "Japanese",
  "Korean",
  "Chinese",
  "Arabic",
  "Hindi",
  "Turkish",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Greek",
  "Czech",
  "Romanian",
  "Hungarian",
  "Ukrainian",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Filipino",
] as const;

export type Language = (typeof LANGUAGES)[number];

// ISO 639-1 codes used by Apple Transcription
export const APPLE_LANGUAGE_CODE_MAP: Record<string, string> = {
  English: "en",
  Spanish: "es",
  French: "fr",
  German: "de",
  Italian: "it",
  Portuguese: "pt",
  Polish: "pl",
  Russian: "ru",
  Japanese: "ja",
  Korean: "ko",
  Chinese: "zh",
  Arabic: "ar",
  Hindi: "hi",
  Turkish: "tr",
  Dutch: "nl",
  Swedish: "sv",
  Norwegian: "no",
  Danish: "da",
  Finnish: "fi",
  Greek: "el",
  Czech: "cs",
  Romanian: "ro",
  Hungarian: "hu",
  Ukrainian: "uk",
  Vietnamese: "vi",
  Thai: "th",
  Indonesian: "id",
  Malay: "ms",
  Filipino: "fil",
};

// ISO 639-2 codes used by ElevenLabs Speech-to-Text
export const ELEVENLABS_LANGUAGE_CODES: Record<string, string> = {
  English: "eng",
  Spanish: "spa",
  French: "fra",
  German: "deu",
  Italian: "ita",
  Portuguese: "por",
  Polish: "pol",
  Russian: "rus",
  Japanese: "jpn",
  Korean: "kor",
  Chinese: "zho",
  Arabic: "ara",
  Hindi: "hin",
  Turkish: "tur",
  Dutch: "nld",
  Swedish: "swe",
  Norwegian: "nor",
  Danish: "dan",
  Finnish: "fin",
  Greek: "ell",
  Czech: "ces",
  Romanian: "ron",
  Hungarian: "hun",
  Ukrainian: "ukr",
  Vietnamese: "vie",
  Thai: "tha",
  Indonesian: "ind",
  Malay: "msa",
  Filipino: "fil",
};

// ISO 639-1 codes used by ElevenLabs TTS
export const TTS_LANGUAGE_CODES: Record<string, string> = {
  English: "en",
  Spanish: "es",
  French: "fr",
  German: "de",
  Italian: "it",
  Portuguese: "pt",
  Polish: "pl",
  Russian: "ru",
  Japanese: "ja",
  Korean: "ko",
  Chinese: "zh",
  Arabic: "ar",
  Hindi: "hi",
  Turkish: "tr",
  Dutch: "nl",
  Swedish: "sv",
  Norwegian: "no",
  Danish: "da",
  Finnish: "fi",
  Greek: "el",
  Czech: "cs",
  Romanian: "ro",
  Hungarian: "hu",
  Ukrainian: "uk",
  Vietnamese: "vi",
  Thai: "th",
  Indonesian: "id",
  Malay: "ms",
  Filipino: "fil",
};

export const VOICE_IDS: Record<string, string> = {
  English: "21m00Tcm4TlvDq8ikWAM",
  Spanish: "EXAVITQu4vr4xnSDxMaL",
  French: "ThT5KcBeYPX3keUQqHPh",
  German: "pNInz6obpgDQGcFmaJgB",
  Italian: "VR6AewLTigWG4xSOukaG",
  Portuguese: "AZnzlk1XvdvUeBnXmlld",
  Japanese: "Yko7PKs6WkR5f4b8g0Zj",
  Korean: "jsCqWAovK2LkecY7zXl4",
  Chinese: "g5CIjZEefAph4nQFvHAz",
  default: "21m00Tcm4TlvDq8ikWAM",
};

// Helsinki-NLP model mapping for supported language pairs
export const HELSINKI_MODEL_MAP: Record<string, string> = {
  "English-Italian": "opus-mt-en-it",
  "English-Spanish": "opus-mt-en-es",
  "English-French": "opus-mt-en-fr",
  "English-German": "opus-mt-en-de",
  "English-Portuguese": "opus-mt-en-pt",
  "English-Russian": "opus-mt-en-ru",
  "English-Chinese": "opus-mt-en-zh",
  "English-Japanese": "opus-mt-en-jap",
  "English-Arabic": "opus-mt-en-ar",
  "English-Dutch": "opus-mt-en-nl",
  "English-Polish": "opus-mt-en-pl",
  "English-Turkish": "opus-mt-en-tr",
  "English-Swedish": "opus-mt-en-sv",
  "English-Norwegian": "opus-mt-en-no",
  "English-Danish": "opus-mt-en-da",
  "English-Finnish": "opus-mt-en-fi",
  "English-Greek": "opus-mt-en-el",
  "English-Czech": "opus-mt-en-cs",
  "English-Romanian": "opus-mt-en-ro",
  "English-Hungarian": "opus-mt-en-hu",
  "English-Ukrainian": "opus-mt-en-uk",
  "English-Vietnamese": "opus-mt-en-vi",
  "English-Thai": "opus-mt-en-th",
  "English-Indonesian": "opus-mt-en-id",
  "English-Korean": "opus-mt-en-ko",
  "English-Hindi": "opus-mt-en-hi",
  "Italian-English": "opus-mt-it-en",
  "Italian-Spanish": "opus-mt-it-es",
  "Italian-French": "opus-mt-it-fr",
  "Italian-German": "opus-mt-it-de",
  "Spanish-English": "opus-mt-es-en",
  "Spanish-Italian": "opus-mt-es-it",
  "Spanish-French": "opus-mt-es-fr",
  "Spanish-German": "opus-mt-es-de",
  "Spanish-Portuguese": "opus-mt-es-pt",
  "French-English": "opus-mt-fr-en",
  "French-Italian": "opus-mt-fr-it",
  "French-Spanish": "opus-mt-fr-es",
  "French-German": "opus-mt-fr-de",
  "German-English": "opus-mt-de-en",
  "German-Italian": "opus-mt-de-it",
  "German-Spanish": "opus-mt-de-es",
  "German-French": "opus-mt-de-fr",
  "Portuguese-English": "opus-mt-pt-en",
  "Portuguese-Spanish": "opus-mt-pt-es",
  "Russian-English": "opus-mt-ru-en",
  "Chinese-English": "opus-mt-zh-en",
  "Japanese-English": "opus-mt-jap-en",
  "Dutch-English": "opus-mt-nl-en",
  "Dutch-German": "opus-mt-nl-de",
  "Polish-English": "opus-mt-pl-en",
  "Turkish-English": "opus-mt-tr-en",
  "Arabic-English": "opus-mt-ar-en",
  "Swedish-English": "opus-mt-sv-en",
  "Norwegian-English": "opus-mt-no-en",
  "Danish-English": "opus-mt-da-en",
  "Finnish-English": "opus-mt-fi-en",
  "Greek-English": "opus-mt-el-en",
  "Czech-English": "opus-mt-cs-en",
  "Romanian-English": "opus-mt-ro-en",
  "Hungarian-English": "opus-mt-hu-en",
  "Ukrainian-English": "opus-mt-uk-en",
  "Vietnamese-English": "opus-mt-vi-en",
  "Thai-English": "opus-mt-th-en",
  "Indonesian-English": "opus-mt-id-en",
  "Korean-English": "opus-mt-ko-en",
  "Hindi-English": "opus-mt-hi-en",
};

// 2-letter language codes for Helsinki models
export const HELSINKI_LANGUAGE_CODE_MAP: Record<string, string> = {
  English: "en",
  Italian: "it",
  Spanish: "es",
  French: "fr",
  German: "de",
  Portuguese: "pt",
  Russian: "ru",
  Chinese: "zh",
  Japanese: "jap",
  Arabic: "ar",
  Dutch: "nl",
  Polish: "pl",
  Turkish: "tr",
  Swedish: "sv",
  Norwegian: "no",
  Danish: "da",
  Finnish: "fi",
  Greek: "el",
  Czech: "cs",
  Romanian: "ro",
  Hungarian: "hu",
  Ukrainian: "uk",
  Vietnamese: "vi",
  Thai: "th",
  Indonesian: "id",
  Korean: "ko",
  Hindi: "hi",
  Malay: "ms",
  Filipino: "tl",
};

export function getLanguageNameFromCode(code: string | undefined): string {
  if (!code) return "Unknown";
  const map: Record<string, string> = {
    eng: "English",
    spa: "Spanish",
    fra: "French",
    deu: "German",
    ita: "Italian",
    por: "Portuguese",
    pol: "Polish",
    rus: "Russian",
    jpn: "Japanese",
    kor: "Korean",
    zho: "Chinese",
    cmn: "Chinese",
    ara: "Arabic",
    hin: "Hindi",
    tur: "Turkish",
    nld: "Dutch",
    swe: "Swedish",
    nor: "Norwegian",
    dan: "Danish",
    fin: "Finnish",
    ell: "Greek",
    ces: "Czech",
    ron: "Romanian",
    hun: "Hungarian",
    ukr: "Ukrainian",
    vie: "Vietnamese",
    tha: "Thai",
    ind: "Indonesian",
    msa: "Malay",
    fil: "Filipino",
  };
  return map[code] || code;
}
